version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  CSS_MODE: ${CSS_MODE-optimized}
  BING_API_KEY: ${BING_API_KEY-}
  GTM_CONTAINER_ID: ${GTM_CONTAINER_ID}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: support@parameter1.com
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://browse.tauron.mindful-web.parameter1.com/graphql}
  USE_LINK_INJECTED_BODY: ${USE_LINK_INJECTED_BODY-false}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.tauron.mindful-web.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.tauron.mindful-web.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.tauron.mindful-web.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.tauron.mindful-web.parameter1.com}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  bizbash:
    <<: *site-cmd
    working_dir: /root/sites/bizbash.com
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 12195
      LIVERELOAD_PORT: 35195
    ports:
      - "12195:80"
      - "35195:35195"
